### PR TITLE
New TTree Writing Code

### PR DESCRIPTION
**Pull request by beojan**
This is the new TTree writing code that makes adding new branches a lot easier.
I've also switched the LCG release to LCG dev4, since we need the latest patches for ROOT.

`setup.sh` also needs to be updated to load the custom Delphes install with @jenesis360's changes, but we can deal with that later.

### CODE REVIEW

**Comment by sparedes** [comment]
I believe RDataFrames already have functionality to write out TTrees ( i.e. the 'Snapshot' method here https://root.cern/doc/master/classROOT_1_1RDataFrame.html ). 
Wouldn't this work for us?

**Comment by beojan** [comment]
No, it doesn't. We need to unpack our event object.

**Comment by sparedes** [comment]
We can easily unpack it in the code itself, maybe using a lambda?
I think this way it will be a lot more readable and easier to add/remove branches.

**Comment by beojan** [comment]
That would require `Define`ing a new column for each branch, which would clutter the `main` function, since you can't put the `Define`s elsewhere. You also can't `Snapshot` into an open `TFile`. You have to close the file and `Snapshot` into the file*name*, being careful not to overwrite it.

 > I think this way it will be a lot more readable and easier to add/remove branches.

That was the point of the PR. To add a branch, you just need to add an entry to the `output_format` object in `utils.h`, with the branch name and a lambda which generates it from our `event` object. A `Define` would actually require *more* boilerplate, because you have to pass the column list `{"event"}` manually to each call.

**Comment by beojan** [comment]
Now produces the same number of events as master.

**Comment by beojan** [comment]
Any objections to merging this?

**Comment by beojan** [comment]
Closing for now.

**Pull request closed without merging**
